## Accessing data from a text file

In [1]:
import numpy as np

In [2]:
filedata=np.genfromtxt("data.txt",delimiter=",") # by default this gives a floating point

In [3]:
filedata=filedata.astype("int32") # using astype to typecast to int32

In [4]:
filedata

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13],
       [  2,   3,   5,   7,  11,  13,  17,  19,  23,  29,  31,  37,  41]],
      dtype=int32)

In [5]:
filedata>13

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False],
       [False, False, False, False, False, False,  True,  True,  True,
         True,  True,  True,  True]])

In [6]:
filedata[filedata>13]

array([ 20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,  17,
        19,  23,  29,  31,  37,  41], dtype=int32)

In [7]:
np.any(filedata>13,axis=0)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [8]:
np.all(filedata>13,axis=0)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False])