## Array creation: Conversion from other Python Structures

In [2]:
import numpy as np

In [3]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
listarray.shape

(3, 3)

In [6]:
listarray.dtype #by default the dtype is 64

dtype('int64')

## Array Creation: Using Intrinsic Objects

In [7]:
zeros=np.zeros((2,3))

In [8]:
zeros #creates a numpy array of zeros with dtype float

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
zeros.dtype

dtype('float64')

In [10]:
zeros.shape

(2, 3)

In [11]:
array1=np.arange(15)

In [12]:
array1 #array of elements from 0 to n-1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
lspace=np.linspace(0,50,10) #gives 10 elements which are equally spaced from each other

In [14]:
lspace

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [15]:
lspace.dtype

dtype('float64')

In [16]:
lspace.shape

(10,)