## Array creation: Conversion from other Python Structures

In [1]:
import numpy as np

In [2]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
listarray.shape

(3, 3)

In [5]:
listarray.dtype #by default the dtype is 64

dtype('int64')

## Array Creation: Using Intrinsic Objects

In [6]:
zeros=np.zeros((2,3)) #creates a numpy array of zeros with dtype float

In [7]:
zeros 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
zeros.dtype

dtype('float64')

In [9]:
zeros.shape

(2, 3)

In [10]:
array1=np.arange(15) #array of elements from 0 to n-1

In [11]:
array1 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
lspace=np.linspace(0,50,10) #gives 10 elements which are equally spaced from each other

In [13]:
lspace

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [14]:
lspace.dtype

dtype('float64')

In [15]:
lspace.shape

(10,)

In [16]:
emp_like=np.empty_like(lspace) #creates a duplicate array of an already existing array 

In [17]:
emp_like 

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [18]:
iden=np.identity(3) #creates a nxn identity matrix

In [19]:
iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
arr=np.arange(99)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [22]:
arr=arr.reshape(3,33) #takes 2 inputs which on multiplying mut give back the original number

In [23]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [24]:
arr=arr.ravel() #ravel is used to reshape it back to its original form

In [25]:
arr.shape

(99,)

In [26]:
arr2=np.ones((3,3))

In [27]:
arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
arr2.dtype

dtype('float64')

In [29]:
arr3=np.full((3,3),5) #takes the shape and the number to be filled

In [30]:
arr3

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [31]:
arr4=np.full_like(lspace,10) #takes an array and a number to replace all the elements to

In [32]:
arr4

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

In [33]:
arr5=np.random.rand(3,3) #random decimal values within 0-1

In [34]:
arr5

array([[0.79213892, 0.6230922 , 0.57194909],
       [0.42930886, 0.91050111, 0.68806377],
       [0.80253226, 0.84708003, 0.14274005]])

In [35]:
arr6=np.random.randint(3,9,size=(3,3)) #random integers from 3 to 9

In [36]:
arr6

array([[4, 7, 7],
       [3, 6, 5],
       [7, 5, 6]])