## Numpy arrays and its usefullness in Mathematics

### All these mathematical operations wouldn't work how they should on lists

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])

In [3]:
a+2

array([3, 4, 5, 6])

In [4]:
a*2

array([2, 4, 6, 8])

In [5]:
b=np.array([4,3,2,1])

In [6]:
a+b

array([5, 5, 5, 5])

In [7]:
a*b

array([4, 6, 6, 4])

### Linear Algebra

In [8]:
arr1=np.ones((2,3),dtype='int8')

In [9]:
arr2=np.full((3,2),2)

In [10]:
arr3=np.matmul(arr1,arr2) # for multiplying 2 matrices use matmul method

In [11]:
arr3

array([[6, 6],
       [6, 6]])

In [12]:
arr4=np.identity(3)

In [13]:
np.linalg.det(arr4) # to get determinant of a matrix just use linalg.det

1.0

### Statistics

In [23]:
st1=np.array([[1,2,3],[1,5,1]])

In [24]:
st1.min()

1

In [25]:
st1.min(axis=1)

array([1, 1])

In [26]:
st1.max()

5

In [27]:
st1.max(axis=0)

array([1, 5, 3])

In [28]:
st1.sum()

13

In [29]:
st1.mean()

2.1666666666666665

In [30]:
st1.std() # computes standard deviation

1.4624940645653537

In [31]:
st1.var() # computes variance

2.138888888888889

In [33]:
np.median(st1)

1.5