## Numpy arrays and its usefullness in Mathematics

### All these mathematical operations wouldn't work how they should on lists

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])

In [3]:
a+2

array([3, 4, 5, 6])

In [4]:
a*2

array([2, 4, 6, 8])

In [5]:
b=np.array([4,3,2,1])

In [6]:
a+b

array([5, 5, 5, 5])

In [7]:
a*b

array([4, 6, 6, 4])

### Linear Algebra

In [12]:
arr1=np.ones((2,3),dtype='int8')

In [13]:
arr2=np.full((3,2),2)

In [14]:
arr3=np.matmul(arr1,arr2) #for multiplying 2 matrices use matmul method

In [15]:
arr3

array([[6, 6],
       [6, 6]])

In [19]:
arr4=np.identity(3)

In [20]:
np.linalg.det(arr4) #to get determinant of a matrix just use linalg.det

1.0

### Statistics

In [21]:
st1=np.array([[1,2,3],[4,5,6]])

In [22]:
st1.min()

1

In [23]:
st1.min(axis=1)

array([1, 4])

In [25]:
st1.max()

6

In [26]:
st1.max(axis=0)

array([4, 5, 6])

In [27]:
st1.sum()

21