## Numpy Axis

In [1]:
#1D array -> Axis 0
#2D array -> Axis 0,Axis 1
#Axis 0 -> Along Columns
#Axis 1 -> Along Rows

In [1]:
import numpy as np

In [2]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [3]:
arr=np.array(x)

In [4]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [5]:
arr.sum(axis=0) # calculates the sum along the columns

array([12,  8,  9])

In [6]:
arr.sum(axis=1) # calculates the sum along the rows

array([ 6, 15,  8])

In [7]:
arr.T # gives the transpose of the array

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [8]:
arr.ndim # gives the dimension of the array

2

In [9]:
arr.nbytes # gives the number of bytes being used by the array

72

In [10]:
one=np.array([1,5,2,4,3])

In [11]:
one.argmax() # gives the index where the max element is located

1

In [12]:
one.argmin() # gives the index where the min element is located

0

In [13]:
one.argsort() # gives the indices which can be used to get the sorted array

array([0, 2, 4, 3, 1])

In [14]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [15]:
arr.argmin(axis=0) # gives an array of index positions of the min elements along the column

array([0, 2, 2])

In [16]:
arr.argmin(axis=1) # gives an array of index positions of the min elements along the row

array([0, 0, 2])

In [17]:
arr.ravel() # flattens the ndarray

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [21]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [22]:
arr.max()

7

In [23]:
arr.min()

0

In [24]:
np.where(arr>5)

(array([1, 2]), array([2, 0]))

In [25]:
np.count_nonzero(arr)

8