# Introduction to Numpy

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
arr1=np.array([2,4,6,8],np.int8) #the elements will use atmost 8 bits 

In [5]:
arr1

array([2, 4, 6, 8], dtype=int8)

In [6]:
arr1[2] #similar to lists we can do indexing

6

In [7]:
arr1.shape #gives us no_of_rows,no_of_columns

(4,)

In [8]:
arr1.dtype #gives us how many bits the number can use

dtype('int8')

In [11]:
arr1[3]=9 #mutable

In [12]:
arr1

array([2, 4, 6, 9], dtype=int8)